model:
  name: "gpt2"
  save_path: "./models/poems"
  save_path2: "./models/sonnets"

data:
  form: "data/form_poems.txt"
  topic: "data/topic_poems.txt"
  shakespeare: "data/shakespeare.txt"

training:
  output_dir: "./results"
  epochs: 5
  batch_size: 4
  save_steps: 500
  max_steps: 1000
