model:
  name: "gpt2"
  save_path: "./results/poems"
  save_path2: "./results/william"

data:
  form: "data/form_poems.txt"
  topic: "data/topic_poems.txt"
  shakespeare: "data/shakespeare.txt"

training:
  output_dir: "./results"
  epochs: 3
  batch_size: 4
  save_steps: 10
  max_steps: 1000
